import{a as I,S as M,i as f}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const H="https://pixabay.com/api/",O="46847728-6b7b012d3b9a78a4f273a5faa",m=15,h=async(t,r)=>{const{data:{hits:o,totalHits:n}}=await I.get(H,{params:{key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:m}});return{images:o,totalHits:n}},L=document.querySelector(".gallery"),v=new M(".gallery a",{overlayOpacity:.8,captions:!0,captionDelay:250,captionPosition:"bottom",captionType:"attr",captionsData:"alt"});let i="";const b=(t,r=!1)=>{r&&(i=""),i=t.reduce((o,{webformatURL:n,largeImageURL:e,tags:s,likes:c,views:q,comments:w,downloads:P})=>o+`<li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img
            class="gallery-image"
            src="${n}"
            alt="${s}"
          />
          <div class="description">
            <span class="description-item"><span>Likes</span> ${c}</span>
            <span class="description-item"><span>Views</span> ${q}</span>
            <span class="description-item"><span>Comments</span> ${w}</span>
            <span class="description-item"><span>Downloads</span> ${P}</span>
          </div>
        </a>
      </li>`,i),L.innerHTML=i,v.refresh()},u=(t,r)=>{if(r===1){t[0].classList.toggle("loading");return}t[1].classList.toggle("loading")},g=(t,r=!0)=>{if(r){t.classList.add("is-visible");return}t.classList.remove("is-visible")},T=()=>{i="",L.innerHTML=i,v.refresh()},y=document.querySelector(".search-form"),S=document.querySelector(".error"),d=document.querySelectorAll(".loader"),p=document.querySelector(".load-more-button");let l="",a=1,E=0;const $=t=>{S.innerHTML="",l=t.target.value.trim()};y.addEventListener("input",$);const D=async t=>{if(t.preventDefault(),a=1,g(p,!1),T(),console.log(l),!l){S.innerHTML="Please add search keyword";return}u(d,a);const{images:r,totalHits:o}=await h(l,a);if(u(d,a),b(r,!0),y.reset(),l="",!r.length){f.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=document.querySelector(".gallery-item");document.querySelector(".gallery-image").addEventListener("load",()=>{E=n.getBoundingClientRect().height}),a*m<o&&g(p)};y.addEventListener("submit",D);const _=async t=>{t.preventDefault(),a+=1,u(d,a);const{images:r,totalHits:o}=await h(l,a);console.log(o),u(d,a),b(r),window.scrollBy({top:E*2,behavior:"smooth"}),a*m>o&&(g(p,!1),f.info({message:"We're sorry, but you've reached the end of search results"}))};p.addEventListener("click",_);
//# sourceMappingURL=index.js.map
