import{a as P,S as H,i as f}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const T="https://pixabay.com/api/",O="46847728-6b7b012d3b9a78a4f273a5faa",m=15,h=async(t,r)=>{const{data:{hits:a,totalHits:n}}=await P.get(T,{params:{key:O,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:m}});return{images:a,totalHits:n}},p=document.querySelector(".gallery"),L=new H(".gallery a",{overlayOpacity:.8,captions:!0,captionDelay:250,captionPosition:"bottom",captionType:"attr",captionsData:"alt"}),b=(t,r=!1)=>{r&&(p.innerHTML="");const a=t.reduce((n,{webformatURL:e,largeImageURL:s,tags:i,likes:E,views:q,comments:I,downloads:M})=>n+`<li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img
            class="gallery-image"
            src="${e}"
            alt="${i}"
          />
          <div class="description">
            <span class="description-item"><span>Likes</span> ${E}</span>
            <span class="description-item"><span>Views</span> ${q}</span>
            <span class="description-item"><span>Comments</span> ${I}</span>
            <span class="description-item"><span>Downloads</span> ${M}</span>
          </div>
        </a>
      </li>`,"");p.insertAdjacentHTML("beforeend",a),L.refresh()},c=(t,r)=>{if(r===1){t[0].classList.toggle("loading");return}t[1].classList.toggle("loading")},g=(t,r=!0)=>{if(r){t.classList.add("is-visible");return}t.classList.remove("is-visible")},$=()=>{p.innerHTML="",L.refresh()},y=document.querySelector(".search-form"),v=document.querySelector(".error"),d=document.querySelectorAll(".loader"),u=document.querySelector(".load-more-button");let l="",S="",o=1,w=0;const A=t=>{v.innerHTML="",l=t.target.value.trim()};y.addEventListener("input",A);const D=async t=>{if(t.preventDefault(),$(),S=l,o=1,g(u,!1),!l){v.innerHTML="Please add search keyword";return}c(d,o);const{images:r,totalHits:a}=await h(l,o);if(c(d,o),b(r,!0),y.reset(),l="",!r.length){f.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=document.querySelector(".gallery-item");document.querySelector(".gallery-image").addEventListener("load",()=>{w=n.getBoundingClientRect().height}),o*m<a&&g(u)};y.addEventListener("submit",D);const _=async t=>{t.preventDefault(),o+=1,c(d,o);const{images:r,totalHits:a}=await h(S,o);c(d,o),b(r),window.scrollBy({top:w*2,behavior:"smooth"}),o*m>a&&(g(u,!1),f.info({message:"We're sorry, but you've reached the end of search results"}))};u.addEventListener("click",_);
//# sourceMappingURL=index.js.map
